# .github/FUNDING.yml

# Ko-fi (note the underscore)
ko_fi: nikmedoed         # → https://ko-fi.com/nikmedoed

# Buy Me a Coffee
buy_me_a_coffee: nikmedoed  # → https://buymeacoffee.com/nikmedoed

# До 4 произвольных ссылок в custom
custom:
  - https://boosty.to/nikmedoed/donate
  - https://paypal.me/etonikmedoed
  - https://yoomoney.ru/to/4100119049495394
