baseURL = "https://nikmedoed.github.io/"
languageCode = "en-us"
title = "Nikita Muromtsev"

[params]
# Optional endpoint that receives contact form submissions
contact_endpoint = ""
# Address used when falling back to an email link
contact_email = "nikmedoed@example.com"
