baseURL = "https://nikmedoed.github.io/"
languageCode = "en-us"
title = "Nikita Muromtsev"

[params]
# Endpoint for the contact form. Leave empty or remove if not using Formspree.
formspree_endpoint = ""
