baseURL = "https://nikmedoed.github.io/"
defaultContentLanguage = "en"
# defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content"
  [languages.ru]
    languageName = "Русский"
    weight = 2
    contentDir = "content"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
