baseURL = "https://nikmedoed.com/"
defaultContentLanguage = "en"
# Default language for the site
languageCode = "en"
enableRobotsTXT = true
[sitemap]
  changefreq = "monthly"
  priority = 0.5
# defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content"
  [languages.ru]
    languageName = "Русский"
    weight = 2
    contentDir = "content"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
